version: '3.8'
services:
 rabbitmq:
  image: rabbitmq:3.10.5-management
  container_name: 'rabbitmq'
  environment:
   RABBITMQ_DEFAULT_USER: 'rabbitmq'
   RABBITMQ_DEFAULT_PASS: 'rabbitmq'
  ports:
   - 5672:5672
   - 15672:15672

  volumes:
   - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
   - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

 mailhog:
  image: mailhog/mailhog:latest
  restart: always
  ports:
   - 1025:1025
   - 8025:8025

 postgres:
  image: postgres:15.7
  restart: unless-stopped
  container_name: postgres-15.7
  environment:
   POSTGRES_USER: 'postgres'
   POSTGRES_PASSWORD: 'postgres'
  ports:
   - 5432:5432
  volumes:
   - ~/.docker-conf/postgre/data:/var/lib/postgre/data
