server:
 port: 8081
 
logging:
 level:
  com.github.joanersoncosta.apiprocessador: ${LOG_LEVEL:DEBUG} 

spring:
 application:
  name: api-processador 
 rabbitmq:
  host: localhost
  port: 5672
  username: user
  password: user
  listener:
   simple:
    retry:
     enabled: true
     max-attempts: 2
     initial-interval: 5000
     max-interval: 10000
    default-requeue-rejected: false  # Não reenvia mensagens rejeitadas para a fila
    dead-letter-exchange-type: direct
    dead-letter-exchange: pedidos.v1.pedido-criado.dlq
    dead-letter-routing-key: dead-letter
    
 datasource:
  url: jdbc:postgresql://localhost:5432/pedidos_api
  driver-class-name: org.postgresql.Driver
  username: postgres
  password: admin

 jpa:
  show-sql: false
  hibernate: 
   ddl-auto: update
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect  
      
#RABBITMQ COSTOM CONFIG
rabbitmq:
 exchange:
  name: pedidos.v1.pedido-criado
  notificacao: pedidos.v1.pedido-notificacao
 queue:
  name: pedidos.v1.pedido-criado.gerar-processamento 
  dead-letter: pedidos.v1.pedido-criado.dlq