spring:
 application:
  name: api-pedido
 rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmq
    password: rabbitmq

#SPRINGDOC OPENAPI
springdoc:
 swagger-ui:
  path: /api-docs.html
 api-docs:
  path: /api-docs
 packagesToScan: com.github.joanersoncosta.pedidos.api.pedido.application.api