server:
 servlet:
  context-path: /api
 port: 8082
logging:
 level:
  com.github.joanersoncosta.apipedido: ${LOG_LEVEL:DEBUG} 

spring:
 application:
  name: api-pedido
 rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmq
    password: rabbitmq

 datasource:
  url: jdbc:postgresql://localhost:5432/api_pedido
  driver-class-name: org.postgresql.Driver
  username: postgres
  password: admin

 jpa:
  show-sql: true
  hibernate: 
   ddl-auto: update
   
#SPRINGDOC OPENAPI
springdoc:
 swagger-ui:
  path: /api-docs.html
 api-docs:
  path: /api-docs
 packagesToScan: com.github.joanersoncosta.apipedido.pedido.application.api
 
#RABBITMQ COSTOM CONFIG
rabbitmq:
 exchange:
  name: pedidos.v1.pedido-criado